version: '3'

includes:
  root:
    taskfile: ../Taskfile.yaml
    flatten: true
    vars:
      PACKAGE_MANAGER: uv

vars:
  PWD:
    sh: pwd
  DAGSTER_HOME: "{{.PWD}}/dagster"
  DAGSTER_DEFAULT_FILE: src/dagster_play.py

dotenv: ['.env']

tasks:
  dagster:run:
    desc: Run Dagster job
    cmds:
      - |
        if [ "{{.CLI_ARGS}}" != "" ]; then
          DAGSTER_HOME="{{.DAGSTER_HOME}}" uv run dagster job execute {{.CLI_ARGS}}
        else
          DAGSTER_HOME="{{.DAGSTER_HOME}}" uv run dagster job execute -f {{.DAGSTER_DEFAULT_FILE}} -j __ASSET_JOB
        fi

  dagster:dev:
    desc: Run Dagster dev server
    cmds:
      - |
        if [ "{{.CLI_ARGS}}" != "" ]; then
          DAGSTER_HOME="{{.DAGSTER_HOME}}" uv run dagster dev {{.CLI_ARGS}}
        else
          DAGSTER_HOME="{{.DAGSTER_HOME}}" uv run dagster dev -f {{.DAGSTER_DEFAULT_FILE}}
        fi
