extract:
  backoff:
    retry_wait_min: 1s
    retry_wait_max: 30s
    retry_max: 5

duckdb:
  append_table: daily_adjusted
  conn_init_fn_queries:
    # - "../sql/db__stage.sql"
    - "../sql/table__last_trading_day.sql"
    - "../sql/table__daily_adjusted.sql"
    - "../sql/table__supported_tickers.sql"
    - "../sql/view__selected_us_tickers.sql"
    - "../sql/view__selected_last_trading_day.sql"

tiingo:
  eod:
    format: csv
    start_date: "1995-01-01"
    columns: "date,close,adjClose,adjVolume"
  fundamentals:
    daily:
      format: csv
      start_date: "1995-01-01"
      columns: "date,close,adjClose,adjVolume"

