
duckdb:
  extract:
    backoff:
      retry_wait_min: 1s
      retry_wait_max: 30s
      retry_max: 5
duckdb:
  path: "test.db"
  append_table: daily_adjusted
tiingo:
  eod:
    format: csv
    start_date: "1995-01-01"
    columns: "foo,bar"
