name: keep-repo-active
on:
  schedule:
    - cron: '0 0 1 * *'  # Runs monthly
jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create activity
        run: |
          date > last_updated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update last_updated.txt to keep repository active"
          git push
