name: stage__update-statements

on:
  workflow_dispatch:

jobs:
  run-statements:
    uses: ./.github/workflows/update-fundamentals.yaml
    with:
      environment: 'stage'
      fundamentals_type: 'statements'
    secrets: inherit
